### ISSUE TITLE
Don't assume MSVC version

### ISSUE THREAD

**Issue by ethan-tqa** [BennyQBD/CGFX5#3]
Currently, inside Windows-GenVisualStudioProject.bat, the command to invoke CMake is assuming that user has MSVC 11 installed, which may not be true. Simply reduce that command to:

`cmake ../`

allows CMake to automatically pickup the compiler that is present on the system.

**Comment by jorolf** [comment]
Can confirm, I only have Visual Studio 2017 installed and the .bat didn't work.
After changing the parameter from "Visual Studio 11" to "Visual Studio 15" everything worked

**Comment by BennyQBD** [comment]
Should be fixed now. Please make sure it's still selecting the correct version, but if so I think we can close this.

**Comment by jorolf** [comment]
Works now!

**Comment by BennyQBD** [comment]
Based on feedback this appears to be fixed. Closing.
