### ISSUE TITLE
MSVC Warnings

### ISSUE THREAD

**Issue by falki147** [BennyQBD/CGFX5#6]
Turning /Wall on MSVC on causes it to produce ~14000 warnings. I suggest turning it off or change the warning level (4 seems to be ok) for the MSVC generator.

**Comment by BennyQBD** [comment]
Good suggestion. I've made some basic changes in the CMakeLists, please let me know if that fixes it. If so, I think we can close this.

**Comment by falki147** [comment]
Way better. Now it's only about 30 warnings. Thanks!
