### ISSUE TITLE
Visual Studio 2017 crashes when building the project.

### ISSUE THREAD

**Issue by jorolf** [BennyQBD/CGFX5#8]
I haven't done much testing but whenever I build the CGFX5 project it builds until about 1/3 and then crashes.
Can somebody test this on their version as well? I would like to know if this is something "wide-spread" or if this is due to some plugins I have installed.

**Comment by jorolf** [comment]
Building with the msbuild.exe vs17 shipped works though

**Comment by Thundzz** [comment]
On Windows 10 Entreprise Edition, with Visual Studio Community 2017 version 15.6.6, it compiles and runs on my machine.  Maybe you don't have enough memory available on your machine?

If you have any more details on how the program crashes I'm interested in looking a bit more in depth !

**Comment by jorolf** [comment]
Ok I fixed it, it was some problem with a plugin I installed
